// Cross-region travel: Ashbridge → Army (placeholder or real) → back to the Hospice.
import { chromium } from 'playwright-core';
const base = process.argv[2] ?? 'http://127.0.0.1:5191/';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await (await browser.newContext({ viewport: { width: 960, height: 540 } })).newPage();
page.setDefaultTimeout(300000);
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
let failures = 0;
const check = (n, ok) => { console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}`); if (!ok) failures++; };
const ev = (f) => page.evaluate(f);
const until = (fn, t = 120000) => page.waitForFunction(fn, null, { timeout: t, polling: 300 }).catch(() => {});
await page.goto(base + '?skipintro&origin=householdKnight&quality=low&norender');
await page.waitForFunction(() => window.__ready && window.__game.mode === 'play', null, { timeout: 180000 });
check('army locked before Corvane', await ev(() => !window.__session.destinations().some((d) => d.id === 'army.road' && d.unlocked)));
await ev(() => { window.__session.ws.flags['boss.corvane'] = true; window.__session.ws.stillbells.hospice = true; });
check('army and academy open after Corvane', await ev(() => ['army.road', 'academy.causeway'].every((id) => window.__session.destinations().find((d) => d.id === id)?.unlocked)));
check('cathedral still locked', await ev(() => !window.__session.destinations().find((d) => d.id === 'cathedral.gate')?.unlocked));
await ev(() => { window.__session.atBell = { id: 'hospice', name: 'Hospice' }; window.__session.travel('army.road'); });
await until(() => window.__session.region?.id === 'army' && window.__game.player && !window.__game.player.dead);
check('travelled to the Royal Army', await ev(() => window.__session.region.id === 'army' && window.__session.ws.region === 'army'));
await ev(() => window.__session.leaveStillbell());
await until(() => window.__game.mode === 'play');
await ev(() => { window.__session.atBell = { id: 'army.road', name: 'x' }; window.__session.travel('hospice'); });
await until(() => window.__session.region?.id === 'ashbridge' && window.__game.mode === 'menu');
check('travelled back to the Hospice (Ashbridge rebuilt)', await ev(() => window.__session.region.id === 'ashbridge' && window.__game.enemies.length > 5));
check('Corvane stays dead after returning', await ev(() => !window.__session.region.boss));
for (const e of errs) console.log('ERR', e);
console.log(failures ? `\n${failures} FAILED` : '\nALL PASSED');
await browser.close();
process.exit(failures ? 1 : 0);
